/* cvid_asm.h - state block for the assembler block loop.
 *
 * The 0x3100 block loop is by far the most frequent chunk (275 of 345
 * measured) and the only place where gcc is demonstrably worse than hand
 * work on the 68020/030: it runs out of address registers, three
 * of the four row pointers end up in data registers, and before every store
 * there is a `movea.l dN,aX`. The addressing mode (An,Dn.l) that would avoid
 * this is not generated by gcc here - tried and dismissed.
 *
 * A state block is passed instead of many arguments: the routine loads it
 * into the registers on entry, runs, and writes it back on exit.
 * That keeps the C side readable and the register allocation free.
 *
 * The order of the fields is part of the interface - the assembler file
 * addresses them through fixed offsets. The self test in cvid.c checks it
 * against the assembler side.
 */
#ifndef CYBERPAK_CVID_ASM_H
#define CYBERPAK_CVID_ASM_H

#include <stdint.h>

typedef struct {
    const uint8_t *from;     /*  0  read pointer in the bitstream   */
    const uint8_t *cend;     /*  4  end of the chunk                */
    uint8_t       *p0;       /*  8  upper left corner of the block  */
    const uint8_t *cb0;      /* 12  V4 codebook, 16 bytes per entry */
    const uint8_t *cb1;      /* 16  V1 codebook                     */
    const uint8_t *ylimit;   /* 20  lower bound of the strip        */
    int32_t        stride;   /* 24  row distance in bytes           */
    int32_t        binc;     /* 28  block advance (4 * bpp)         */
    int32_t        wrap;     /* 32  row break                       */
    uint32_t       bx;       /* 36  blocks to the end of the row    */
    uint32_t       bcols;    /* 40  blocks per row                  */
    uint8_t       *dirty;    /* 44  current block row, one byte each */
} cvid_loop;

/* `dirty` points to the byte of the block row p0 currently stands in, and
 * is carried along on a row change. The 8-bit version sets it at every
 * written block (`st (a6)`); the 16-bit version does not touch it,
 * but moves the pointer on just the same - the loop frame is
 * shared. On return the current state stands there, so that the
 * C code can continue it across chunk boundaries. */

#define CVID_LOOP_OFF_FROM    0
#define CVID_LOOP_OFF_CEND    4
#define CVID_LOOP_OFF_P0      8
#define CVID_LOOP_OFF_CB0    12
#define CVID_LOOP_OFF_CB1    16
#define CVID_LOOP_OFF_YLIMIT 20
#define CVID_LOOP_OFF_STRIDE 24
#define CVID_LOOP_OFF_BINC   28
#define CVID_LOOP_OFF_WRAP   32
#define CVID_LOOP_OFF_BX     36
#define CVID_LOOP_OFF_BCOLS  40
#define CVID_LOOP_OFF_DIRTY  44
#define CVID_LOOP_SIZE       48

/* Each processes one complete block chunk in the 16-bit output mode and
 * updates from, p0 and bx in the state block.
 *   3100  continuous bitstream: 0 = skip, 10 = V1, 11 = V4
 *   3000  one flag bit per block: 1 = V4, 0 = V1, no skip
 *   For 0x3200 (V1 only) assembler has proved to be a step backwards. */
void cvid_blk3100_rgb16(cvid_loop *st);
void cvid_blk3000_rgb16(cvid_loop *st);

/* The same two chunks for ONE byte per pixel (CVID_OUT_GRAY8). See
 * src/asm/cvid_blk8_020.s; the loops set one byte in `dirty` per block. */
void cvid_blk3100_pix8(cvid_loop *st);
void cvid_blk3000_pix8(cvid_loop *st);

/* And for four bytes per pixel. The most store-heavy mode: 16 longwords per
 * block. From the 68020 on only - RGB32 presupposes a graphics card. */
void cvid_blk3100_rgb32(cvid_loop *st);
void cvid_blk3000_rgb32(cvid_loop *st);
/* For 0x3200 there is deliberately NO assembler version - see cvid_body.h. */


/* --- codebook creation, partial form (0x2100/0x2300) ------------------
 *
 * Measured on goku600a.avi, 208,360 of 211,254 codebook entries run
 * through the PARTIAL form - the full one (0x2000/0x2200) accounts for 1.4 %
 * and therefore stays with the C code. (The synthetic clip test320.avi, the
 * other way round, uses the full form exclusively; whoever measures with
 * that alone thinks the partial one unimportant.)
 *
 * The bitstream is: a 32-bit flag word, then six bytes per set bit
 * (y0,y1,y2,y3,u,v). Bits that are not set skip the entry but still count
 * towards the index. */
typedef struct {
    const uint8_t  *from;    /*  0  read pointer                     */
    const uint8_t  *cend;    /*  4  end of the chunk                 */
    uint8_t        *cm;      /*  8  codebook, 16 bytes per entry     */
    const uint8_t  *cmend;   /* 12  cm + 256*16, guard against ci>=256 */
    const int32_t  *ytab;    /* 16  &yuv_table.yTab[0]               */
    /* The three pre-built clamp tables. WHICH ones they are depends on the
     * output mode: with RGB16 those from yuv_rng16_tables(), with CLUT8 those
     * from yuv_clut_tables(). The routine sees nothing of that - it looks up
     * three values and combines them. */
    const uint32_t *tabr;    /* 20 */
    const uint32_t *tabg;    /* 24 */
    const uint32_t *tabb;    /* 28 */
    /* CVID_OUT_GRAY8 only: quantise to 2^(8-gsh) grey levels. The
     * grey level version uses neither chroma nor the three tables - it
     * shifts Y and packs. That is why the value stands here and not in
     * one of the tables. */
    int32_t         gsh;     /* 32 */
    /* CVID_OUT_PAL8 only: the palq whose search needs a new colour.
     * tabr is R15 there (G15/B15 behind it), tabg the mapping (68000:
     * G15), tabb the validity bytes - see cvid_mkcbpal8_020.s. */
    void           *pq;      /* 36 */
} cvid_mkcb;

#define CVID_MK_OFF_FROM   0
#define CVID_MK_OFF_CEND   4
#define CVID_MK_OFF_CM     8
#define CVID_MK_OFF_CMEND 12
#define CVID_MK_OFF_YTAB  16
#define CVID_MK_OFF_TABR  20
#define CVID_MK_OFF_TABG  24
#define CVID_MK_OFF_TABB  28
#define CVID_MK_OFF_GSH   32
#define CVID_MK_OFF_PQ    36

/* They update `from`. The table offsets relative to ytab:
 * ubTab -4096, vrTab -3072, ugTab -2048, vgTab -1024. */
void cvid_mkcb4p_rgb16(cvid_mkcb *st);   /* 0x2100, V4, 16 bit */
void cvid_mkcb1p_rgb16(cvid_mkcb *st);   /* 0x2300, V1, 16 bit */

/* --- codebook creation, FULL form (0x2000/0x2200) --------------------
 *
 * It is the more frequent one, more so than it looked for a long time:
 * measured over all available clips, the files produced by this project's
 * encoder use the full form EXCLUSIVELY. Only goku600a.avi - from a
 * foreign encoder - uses the partial one. Whoever measures with that alone
 * wrongly thinks the full form the corner case.
 *
 * Simpler than the partial form: no flag word, no bit counter. The
 * entries stand sequentially, six bytes per entry.
 *
 * CAUTION: `cend` has to be the end of the ENTRIES here, not
 * necessarily the end of the chunk - the caller clamps the number of
 * entries. `cmend` additionally limits it to 256 entries. */
void cvid_mkcbfull4_rgb16(cvid_mkcb *st);
void cvid_mkcbfull1_rgb16(cvid_mkcb *st);

/* Grey levels. A version of its own, because it needs neither chroma nor
 * tables - only `gsh` and four Y bytes. It does without 020 addressing modes
 * and is therefore built for EVERY target, the 68000 included. */
void cvid_mkcbfull4_gray(cvid_mkcb *st);
void cvid_mkcbfull1_gray(cvid_mkcb *st);

/* RGB32. Both entry points lead to the same arithmetic - with RGB32
 * the V1 and V4 entries are built identically (four finished ARGB values). */
void cvid_mkcbfull4_rgb32(cvid_mkcb *st);
void cvid_mkcbfull1_rgb32(cvid_mkcb *st);

#endif
