; rtg.s - output on the graphics card (CyberGraphX/Picasso96), 020/030 player.
;
; Model: src/video.c (rtg_open, rtg_show, full screen). A window on the
; Workbench screen; the picture is built as a chunky buffer in fast RAM (rt_fb)
; and goes out ONCE per round: 32 bit with WritePixelArray (RECTFMT_ARGB,
; exactly the memory bytes A,R,G,B), 15/16 bit with p96WritePixelArray and a
; RenderInfo - WritePixelArray has no 15/16-bit source format.
;
; CONSTANTS: the .i files of the CyberGraphX SDK cannot be assembled with vasm.
; rtg.i is generated by tools/pruefstand/mkndk.py from the C headers; the LVOs
; of cybergraphics.library come from lvo/cybergraphics.i.
;
;   rtg_erkennen  -> d0 = 0 usable, RT_E_LIB no graphics card (library missing
;                 or the Workbench does not live on it), RT_E_SCHIRM cannot
;                 lock the Workbench, RT_E_TIEFE below 15 bit (rt_tiefe);
;                 the libraries stay open (rtg_close)
;   rtg_open      d0 = width, d1 = height, d2 = 1: 15/16 bit (HICOLOR)
;                 -> d0 = 0 or RT_E_*; afterwards rt_fb, rt_bpp (4/2),
;                 rt_pix16 (CVX_PIX16_*), rt_stride, rt_zeilen
;   rtg_zeigen    rt_fb into the window
;   rtg_input     -> d0 = 0 nothing, 1 quit, 2 pause, 3 toggle full screen
;   rtg_sigmask   -> d0 = signal mask of the window
;   rtg_vollbild  -> d0 = 0 switched, otherwise RT_F_*
;   rtg_close     any number of times; preserves all registers

        include "player.i"
        include "graphics/gfx.i"
        include "graphics/rastport.i"
        include "graphics/modeid.i"
        include "intuition/intuition.i"
        include "intuition/screens.i"
        include "utility/tagitem.i"
        include "lvo/intuition_lib.i"
        include "lvo/cybergraphics.i"
        include "rtg.i"

        xdef    rtg_erkennen,rtg_open,rtg_zeigen,rtg_input,rtg_sigmask,rtg_vollbild,rtg_close
        xdef    rt_fb,rt_bpp,rt_pix16,rt_stride,rt_zeilen,rt_tiefe,rt_pixfmt,rt_gruende,rt_eigen
        xref    _SysBase

        section code,code

; Open the libraries (once): cybergraphics 41, intuition 36 -> d0 = 0 / RT_E_LIB
libs_oeffnen:
        movem.l d1/a0-a1/a6,-(sp)
        tst.l   rt_cgxbase
        bne     .gut
        lea     intname,a1
        moveq   #36,d0
        EXEC    OpenLibrary
        move.l  d0,rt_intbase
        beq     .fehlt
        lea     cgxname,a1
        moveq   #41,d0
        jsr     _LVOOpenLibrary(a6)
        move.l  d0,rt_cgxbase
        beq     .fehlt
.gut:   moveq   #0,d0
        bra     .raus
.fehlt: moveq   #RT_E_LIB,d0
.raus:  movem.l (sp)+,d1/a0-a1/a6
        rts

; a2 = screen -> rt_tiefe, rt_pixfmt; d0 = ISCYBERGFX (0 = not a card screen)
format_lesen:
        movem.l d1-d2/a0-a1/a6,-(sp)
        move.l  rt_cgxbase,a6
        move.l  sc_RastPort+rp_BitMap(a2),a0
        move.l  #CYBRMATTR_DEPTH,d0
        jsr     _LVOGetCyberMapAttr(a6)
        move.l  d0,rt_tiefe
        move.l  sc_RastPort+rp_BitMap(a2),a0
        move.l  #CYBRMATTR_PIXFMT,d0
        jsr     _LVOGetCyberMapAttr(a6)
        move.l  d0,rt_pixfmt
        move.l  sc_RastPort+rp_BitMap(a2),a0
        move.l  #CYBRMATTR_ISCYBERGFX,d0
        jsr     _LVOGetCyberMapAttr(a6)
        movem.l (sp)+,d1-d2/a0-a1/a6
        rts

rtg_erkennen:
        movem.l d2/a2/a6,-(sp)
        bsr     libs_oeffnen
        tst.l   d0
        bne     .raus
        sub.l   a0,a0
        move.l  rt_intbase,a6
        jsr     _LVOLockPubScreen(a6)
        tst.l   d0
        beq     .schirm
        move.l  d0,a2
        bsr     format_lesen
        move.l  d0,d2
        sub.l   a0,a0
        move.l  a2,a1
        move.l  rt_intbase,a6
        jsr     _LVOUnlockPubScreen(a6)
        moveq   #RT_E_LIB,d0
        tst.l   d2
        beq     .raus
        moveq   #RT_E_TIEFE,d0
        cmp.l   #15,rt_tiefe
        blo     .raus
        moveq   #0,d0
        bra     .raus
.schirm:
        moveq   #RT_E_SCHIRM,d0
.raus:  movem.l (sp)+,d2/a2/a6
        rts

rtg_open:
        movem.l d2-d7/a2-a6,-(sp)
        move.l  d0,rt_w
        move.l  d1,rt_h
        move.l  d2,rt_will16
        bsr     libs_oeffnen
        tst.l   d0
        bne     .fehl
        sub.l   a0,a0
        move.l  rt_intbase,a6
        jsr     _LVOLockPubScreen(a6)
        move.l  d0,rt_pub
        beq     .e_schirm
        move.l  d0,rt_screen
        move.l  d0,a2
        clr.b   rt_eigen
        bsr     format_lesen
        tst.l   d0
        beq     .e_lib
        cmp.l   #15,rt_tiefe
        blo     .e_tiefe
        moveq   #4,d0
        move.l  d0,rt_bpp
        tst.l   rt_will16
        beq     .speicher
        lea     p96name,a1
        moveq   #2,d0
        EXEC    OpenLibrary
        move.l  d0,rt_p96base
        beq     .e_p96
        lea     formate,a0              ; PIXFMT -> CVX_PIX16, RGBFB
        move.l  rt_pixfmt,d0
.f:     move.w  (a0)+,d1
        bmi     .e_format
        move.w  (a0)+,d2
        move.w  (a0)+,d3
        cmp.w   d1,d0
        bne     .f
        moveq   #0,d1
        move.w  d2,d1
        move.l  d1,rt_pix16
        move.w  d3,d1
        move.l  d1,rt_rgbfb
        moveq   #2,d0
        move.l  d0,rt_bpp
.speicher:
        move.l  rt_w,d0
        mulu.w  rt_bpp+2,d0
        move.l  d0,rt_stride
        move.l  rt_h,d1
        moveq   #-4,d2
        and.l   d2,d1
        move.l  d1,rt_zeilen
        mulu.l  d1,d0
        move.l  d0,rt_fblen
        move.l  #MEMF_CLEAR,d1
        EXEC    AllocMem
        move.l  d0,rt_fb
        beq     .e_speicher
        bsr     fenster_auf
        tst.l   d0
        bne     .e_fenster
        moveq   #0,d0
        bra     .raus
.e_lib: moveq   #RT_E_LIB,d0
        bra     .fehl
.e_schirm:
        moveq   #RT_E_SCHIRM,d0
        bra     .fehl
.e_tiefe:
        moveq   #RT_E_TIEFE,d0
        bra     .fehl
.e_p96: moveq   #RT_E_P96,d0
        bra     .fehl
.e_format:
        moveq   #RT_E_FORMAT,d0
        bra     .fehl
.e_speicher:
        moveq   #RT_E_SPEICHER,d0
        bra     .fehl
.e_fenster:
        moveq   #RT_E_FENSTER,d0
.fehl:  move.l  d0,-(sp)
        bsr     rtg_close
        move.l  (sp)+,d0
.raus:  movem.l (sp)+,d2-d7/a2-a6
        rts

; Window with a border on the locked Workbench screen -> d0 = 0 good
fenster_auf:
        movem.l d1-d2/a0-a2/a6,-(sp)
        move.l  rt_screen,a2
        lea     rt_tags,a0
        move.l  #WA_Title,(a0)+
        move.l  #titel,(a0)+
        move.l  #WA_InnerWidth,(a0)+
        move.l  rt_w,(a0)+
        move.l  #WA_InnerHeight,(a0)+
        move.l  rt_zeilen,(a0)+
        moveq   #0,d0                   ; centred if it fits
        move.w  sc_Width(a2),d0
        sub.l   rt_w,d0
        bpl     .l
        moveq   #0,d0
.l:     lsr.l   #1,d0
        move.l  #WA_Left,(a0)+
        move.l  d0,(a0)+
        moveq   #0,d0
        move.w  sc_Height(a2),d0
        sub.l   rt_zeilen,d0
        bpl     .o
        moveq   #0,d0
.o:     lsr.l   #1,d0
        move.l  #WA_Top,(a0)+
        move.l  d0,(a0)+
        move.l  #WA_DragBar,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_DepthGadget,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_CloseGadget,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_Activate,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_SimpleRefresh,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_NoCareRefresh,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_PubScreen,(a0)+
        move.l  a2,(a0)+
        move.l  #WA_IDCMP,(a0)+
        move.l  #IDCMP_CLOSEWINDOW|IDCMP_VANILLAKEY|IDCMP_RAWKEY,(a0)+
        move.l  #TAG_DONE,(a0)+
        clr.l   (a0)+
        sub.l   a0,a0
        lea     rt_tags,a1
        move.l  rt_intbase,a6
        jsr     _LVOOpenWindowTagList(a6)
        move.l  d0,rt_fenster
        beq     .fehlt
        move.l  d0,a0
        moveq   #0,d0
        move.b  wd_BorderLeft(a0),d0
        move.l  d0,rt_links
        move.b  wd_BorderTop(a0),d0
        move.l  d0,rt_oben
        moveq   #0,d0
        bra     .raus
.fehlt: moveq   #1,d0
.raus:  movem.l (sp)+,d1-d2/a0-a2/a6
        rts

; Borderless window across our own screen, picture centred -> d0 = 0 good
fenster_voll:
        movem.l d1-d2/a0-a2/a6,-(sp)
        move.l  rt_screen,a2
        lea     rt_tags,a0
        move.l  #WA_Left,(a0)+
        clr.l   (a0)+
        move.l  #WA_Top,(a0)+
        clr.l   (a0)+
        moveq   #0,d0
        move.w  sc_Width(a2),d0
        move.l  #WA_Width,(a0)+
        move.l  d0,(a0)+
        sub.l   rt_w,d0
        bpl     .l
        moveq   #0,d0
.l:     lsr.l   #1,d0
        move.l  d0,rt_links
        moveq   #0,d0
        move.w  sc_Height(a2),d0
        move.l  #WA_Height,(a0)+
        move.l  d0,(a0)+
        sub.l   rt_zeilen,d0
        bpl     .o
        moveq   #0,d0
.o:     lsr.l   #1,d0
        move.l  d0,rt_oben
        move.l  #WA_Borderless,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_Backdrop,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_Activate,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_SimpleRefresh,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_NoCareRefresh,(a0)+
        move.l  #1,(a0)+
        move.l  #WA_CustomScreen,(a0)+
        move.l  a2,(a0)+
        move.l  #WA_IDCMP,(a0)+
        move.l  #IDCMP_VANILLAKEY|IDCMP_RAWKEY,(a0)+
        move.l  #TAG_DONE,(a0)+
        clr.l   (a0)+
        sub.l   a0,a0
        lea     rt_tags,a1
        move.l  rt_intbase,a6
        jsr     _LVOOpenWindowTagList(a6)
        move.l  d0,rt_fenster
        seq     d0
        and.l   #1,d0
        movem.l (sp)+,d1-d2/a0-a2/a6
        rts

; Close the window, clearing pending messages first (under Forbid).
fenster_zu:
        movem.l d0-d1/a0-a2/a6,-(sp)
        move.l  rt_fenster,d0
        beq     .raus
        move.l  d0,a2
        EXEC    Forbid
.msg:   move.l  wd_UserPort(a2),a0
        jsr     _LVOGetMsg(a6)
        tst.l   d0
        beq     .zu
        move.l  d0,a1
        jsr     _LVOReplyMsg(a6)
        bra     .msg
.zu:    move.l  a2,a0
        move.l  rt_intbase,a6
        jsr     _LVOCloseWindow(a6)
        clr.l   rt_fenster
        EXEC    Permit
.raus:  movem.l (sp)+,d0-d1/a0-a2/a6
        rts

rtg_zeigen:
        movem.l d2-d7/a2/a6,-(sp)
        move.l  rt_fenster,d0
        beq     .raus
        move.l  d0,a1
        move.l  wd_RPort(a1),a1
        cmp.l   #2,rt_bpp
        beq     .p96
        move.l  rt_fb,a0
        moveq   #0,d0
        moveq   #0,d1
        move.l  rt_stride,d2
        move.l  rt_links,d3
        move.l  rt_oben,d4
        move.l  rt_w,d5
        move.l  rt_zeilen,d6
        moveq   #RECTFMT_ARGB,d7
        move.l  rt_cgxbase,a6
        jsr     _LVOWritePixelArray(a6)
        bra     .raus
.p96:   lea     rt_ri,a0
        move.l  rt_fb,gri_Memory(a0)
        move.w  rt_stride+2,gri_BytesPerRow(a0)
        clr.w   gri_pad(a0)
        move.l  rt_rgbfb,gri_RGBFormat(a0)
        moveq   #0,d0
        moveq   #0,d1
        move.l  rt_links,d2
        move.l  rt_oben,d3
        move.l  rt_w,d4
        move.l  rt_zeilen,d5
        move.l  rt_p96base,a6
        jsr     _LVOp96WritePixelArray(a6)
.raus:  movem.l (sp)+,d2-d7/a2/a6
        rts

rtg_sigmask:
        moveq   #0,d0
        move.l  rt_fenster,d1
        beq     .raus
        move.l  d1,a0
        move.l  wd_UserPort(a0),a0
        moveq   #0,d1
        move.b  MP_SIGBIT(a0),d1
        bset    d1,d0
.raus:  rts

rtg_input:
        movem.l d2/a2/a6,-(sp)
        moveq   #0,d2
        move.l  rt_fenster,d0
        beq     .raus
        move.l  d0,a0
        move.l  wd_UserPort(a0),a2
.msg:   move.l  a2,a0
        EXEC    GetMsg
        tst.l   d0
        beq     .raus
        move.l  d0,a1
        move.l  im_Class(a1),-(sp)
        move.w  im_Code(a1),-(sp)
        jsr     _LVOReplyMsg(a6)
        move.w  (sp)+,d1
        move.l  (sp)+,d0
        cmp.l   #IDCMP_CLOSEWINDOW,d0
        beq     .ende
        cmp.l   #IDCMP_VANILLAKEY,d0
        bne     .msg
        cmp.w   #27,d1
        beq     .ende
        cmp.w   #'q',d1
        beq     .ende
        cmp.w   #'Q',d1
        beq     .ende
        cmp.w   #13,d1
        bne     .pause
        cmp.l   #1,d2
        beq     .msg
        moveq   #3,d2
        bra     .msg
.pause: cmp.w   #32,d1
        bne     .msg
        cmp.l   #1,d2
        beq     .msg
        moveq   #2,d2
        bra     .msg
.ende:  moveq   #1,d2
        bra     .msg
.raus:  move.l  d2,d0
        movem.l (sp)+,d2/a2/a6
        rts

; Switch between window and full screen. The pixel format has to stay the same -
; the decoder packs its codebooks for exactly one of them (video.c).
rtg_vollbild:
        movem.l d2-d7/a2-a6,-(sp)
        tst.l   rt_fenster
        beq     .e_fenster
        tst.b   rt_eigen
        bne     .zurueck
        lea     rt_btags,a0             ; a matching graphics card mode
        move.l  #CYBRBIDTG_NominalWidth,(a0)+
        move.l  rt_w,(a0)+
        move.l  #CYBRBIDTG_NominalHeight,(a0)+
        move.l  rt_zeilen,(a0)+
        move.l  #CYBRBIDTG_Depth,(a0)+
        move.l  rt_tiefe,(a0)+
        move.l  #TAG_DONE,(a0)+
        clr.l   (a0)+
        lea     rt_btags,a0
        move.l  rt_cgxbase,a6
        jsr     _LVOBestCModeIDTagList(a6)
        cmp.l   #INVALID_ID,d0
        beq     .e_modus
        lea     rt_stags,a1
        move.l  #SA_DisplayID,(a1)+
        move.l  d0,(a1)+
        move.l  #SA_Depth,(a1)+
        move.l  rt_tiefe,(a1)+
        move.l  #SA_Type,(a1)+
        move.l  #CUSTOMSCREEN,(a1)+
        move.l  #SA_Quiet,(a1)+
        move.l  #1,(a1)+
        move.l  #SA_ShowTitle,(a1)+
        clr.l   (a1)+
        move.l  #TAG_DONE,(a1)+
        clr.l   (a1)+
        sub.l   a0,a0
        lea     rt_stags,a1
        move.l  rt_intbase,a6
        jsr     _LVOOpenScreenTagList(a6)
        tst.l   d0
        beq     .e_schirm
        move.l  d0,a2
        move.l  rt_pixfmt,d2            ; the format has to match
        move.l  rt_tiefe,d3
        bsr     format_lesen
        cmp.l   rt_pixfmt,d2
        beq     .passt
        move.l  d2,rt_pixfmt
        move.l  d3,rt_tiefe
        move.l  a2,a0
        move.l  rt_intbase,a6
        jsr     _LVOCloseScreen(a6)
        moveq   #RT_F_FORMAT,d0
        bra     .raus
.passt: bsr     fenster_zu
        sub.l   a0,a0
        move.l  rt_pub,a1
        move.l  rt_intbase,a6
        jsr     _LVOUnlockPubScreen(a6)
        clr.l   rt_pub
        move.l  a2,rt_screen
        st      rt_eigen
        bsr     fenster_voll
        tst.l   d0
        beq     .gut
        bsr     ins_fenster             ; emergency: back to the Workbench
        moveq   #RT_F_FENSTER,d0
        bra     .raus
.zurueck:
        bsr     ins_fenster
        tst.l   d0
        bne     .raus
.gut:   moveq   #0,d0
        bra     .raus
.e_modus:
        moveq   #RT_F_MODUS,d0
        bra     .raus
.e_schirm:
        moveq   #RT_F_SCHIRM,d0
        bra     .raus
.e_fenster:
        moveq   #RT_F_FENSTER,d0
.raus:  movem.l (sp)+,d2-d7/a2-a6
        rts

; From our own screen back into the window on the Workbench -> d0 = 0 / RT_F_*
ins_fenster:
        movem.l d1/a0-a2/a6,-(sp)
        bsr     fenster_zu
        tst.b   rt_eigen
        beq     .sperren
        move.l  rt_screen,a0
        move.l  rt_intbase,a6
        jsr     _LVOCloseScreen(a6)
        clr.l   rt_screen
        clr.b   rt_eigen
.sperren:
        sub.l   a0,a0
        move.l  rt_intbase,a6
        jsr     _LVOLockPubScreen(a6)
        move.l  d0,rt_pub
        beq     .e_schirm
        move.l  d0,rt_screen
        move.l  d0,a2
        bsr     format_lesen
        bsr     fenster_auf
        tst.l   d0
        bne     .e_fenster
        moveq   #0,d0
        bra     .raus
.e_schirm:
        moveq   #RT_F_SCHIRM,d0
        bra     .raus
.e_fenster:
        moveq   #RT_F_FENSTER,d0
.raus:  movem.l (sp)+,d1/a0-a2/a6
        rts

rtg_close:
        movem.l d0-d1/a0-a1/a6,-(sp)
        bsr     fenster_zu
        move.l  rt_screen,d0
        beq     .fb
        tst.b   rt_eigen
        beq     .pub
        move.l  d0,a0
        move.l  rt_intbase,a6
        jsr     _LVOCloseScreen(a6)
        bra     .schirm_weg
.pub:   move.l  rt_pub,d0
        beq     .schirm_weg
        sub.l   a0,a0
        move.l  d0,a1
        move.l  rt_intbase,a6
        jsr     _LVOUnlockPubScreen(a6)
.schirm_weg:
        clr.l   rt_screen
        clr.l   rt_pub
        clr.b   rt_eigen
.fb:    move.l  rt_fb,d0
        beq     .libs
        move.l  d0,a1
        move.l  rt_fblen,d0
        EXEC    FreeMem
        clr.l   rt_fb
.libs:  lea     rt_p96base,a0
        bsr     .zu
        lea     rt_cgxbase,a0
        bsr     .zu
        lea     rt_intbase,a0
        bsr     .zu
        movem.l (sp)+,d0-d1/a0-a1/a6
        rts
.zu:    move.l  (a0),d0
        beq     .nichts
        clr.l   (a0)
        move.l  d0,a1
        EXEC    CloseLibrary
.nichts:
        rts

        section data,data
cgxname:    dc.b    "cybergraphics.library",0
p96name:    dc.b    "Picasso96API.library",0
intname:    dc.b    "intuition.library",0
titel:      dc.b    "CyberPak",0
                cnop    0,2
; PIXFMT, CVX_PIX16 (src/cpu.h), RGBFB - only the four formats the decoder packs
formate:    dc.w    PIXFMT_RGB16,0,RGBFB_R5G6B5
            dc.w    PIXFMT_RGB16PC,2,RGBFB_R5G6B5PC
            dc.w    PIXFMT_RGB15,1,RGBFB_R5G5B5
            dc.w    PIXFMT_RGB15PC,3,RGBFB_R5G5B5PC
            dc.w    -1
g_lib:      dc.b    "cybergraphics.library is missing or the Workbench is not on the graphics card",0
g_schirm:   dc.b    "the Workbench screen could not be locked",0
g_tiefe:    dc.b    "the Workbench screen has less than 15 bit - the graphics card needs 15 bit or more (change the screen mode)",0
g_fenster:  dc.b    "the window on the Workbench screen could not be opened",0
g_p96:      dc.b    "HICOLOR needs Picasso96API.library - it is missing",0
g_format:   dc.b    "HICOLOR: the screen format is none of the four 15/16 bit formats the decoder can pack for",0
g_speicher: dc.b    "not enough memory for the picture",0
                cnop    0,4
; Reasons for RT_E_1..7
rt_gruende: dc.l    g_lib,g_schirm,g_tiefe,g_fenster,g_p96,g_format,g_speicher

        section bss,bss
rt_intbase: ds.l    1
rt_cgxbase: ds.l    1
rt_p96base: ds.l    1
rt_pub:     ds.l    1
rt_screen:  ds.l    1
rt_fenster: ds.l    1
rt_w:       ds.l    1
rt_h:       ds.l    1
rt_zeilen:  ds.l    1
rt_will16:  ds.l    1
rt_tiefe:   ds.l    1
rt_pixfmt:  ds.l    1
rt_bpp:     ds.l    1
rt_pix16:   ds.l    1
rt_rgbfb:   ds.l    1
rt_stride:  ds.l    1
rt_fb:      ds.l    1
rt_fblen:   ds.l    1
rt_links:   ds.l    1
rt_oben:    ds.l    1
rt_ri:      ds.b    gri_SIZEOF
                cnop    0,4
rt_tags:    ds.l    40
rt_btags:   ds.l    8
rt_stags:   ds.l    12
rt_eigen:   ds.b    1
