# Generates the pair and byte loops of the assembler players: cvidh_blk.s and
# cvidp_blk000.s (68000 and 020/030 player), cvxg8_blk.s, cvxd6_blk.s and
# cvxd8_blk.s (020+ rework) - the byte accesses per variant are spelled out
# instead of typed by hand.
#
# Call (from any directory):  python3 tools/gen_cvidp_blk.py
# Changes to the block loops belong HERE, not in the .s file.
#
# Three parts: the direct routines (into the planes themselves), the same ones
# with a change map (suffix m, for shadow planes in fast RAM) and the copy
# routine that brings what changed into chip RAM.
import os
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
P, RB, BPL = 5, 40, 10240
BASEK = 2               # plane a2 points at (GRAY with 8 planes: 3)
def D(k, r):            # plane k, row r, relative to plane BASEK / row 0
    return (k - BASEK) * BPL + r * RB
def G(g, k):            # byte k of group g of an entry
    return g * P + k
ORDER = [(r, k) for r in range(4) for k in range(P)]    # i = r*P + k
def setp(n):            # number of planes of the routines below (5 PLANAR, 4 HAM6)
    global P, ORDER
    P = n
    ORDER = [(r, k) for r in range(4) for k in range(P)]
LEFT4  = {0: (0, 1, 'd1', 'd2'), 1: (4, 5, 'd1', 'd2'), 2: (0, 1, 'd3', 'd4'), 3: (4, 5, 'd3', 'd4')}
RIGHT4 = {0: (2, 3, 'd1', 'd2'), 1: (6, 7, 'd1', 'd2'), 2: (2, 3, 'd3', 'd4'), 3: (6, 7, 'd3', 'd4')}
DIRTY = 3 * BPL         # Aenderungskarte: sechste "Plane", relativ zu Plane 2
MK = f'        st      {DIRTY}(a2)                    ; Aenderungskarte'
o = []
def e(s=''): o.append(s)

e('''* cvidp_blk.s - Cinepak blocks straight into 5 bitplanes, for EVERY 68k CPU
*
* GENERATED by tools/gen_cvidp_blk.py - change it there, not here: the 20 byte
* accesses per variant are spelled out. Model and yardstick is the C version in
* src/codec/cvidplanar.c; the planar bench checked both frame by frame against
* chunky + C2P.
*
* Fixed geometry of the ECS path: 320 wide, 40 bytes per row, 5 planes linear
* at a distance of 10240 (320x256). cvidp_decode() calls these routines only
* then, otherwise the C path.
*
* ADDRESSING WITHOUT SCALING: a2 points at plane 2, first row of the block row,
* byte of the current column. All 5 planes x 4 rows therefore lie between
* -20480 and +20600 - 16-bit displacements without an index, which the 68000
* can do. Codebook entries are 64 bytes, so the offset is index << 6, and a
* byte inside one lies at 39 at most: (d8,An,Xn.w).
*
* PAIRS: a block is one nibble per plane and row, two blocks are one byte. The
* left block is only prepared - V1: a3 points at its finished 20-byte image in
* the entry; V4: assembled in the scratch buffer of the state. The right one
* writes both as whole bytes. If one half is missing, its nibble in the target
* is preserved (read, mask, write). At the end of a chunk an open left half is
* written the same way with preservation - so the result is exact even when a
* pair reaches across a chunk boundary.
*
*
* ADDRESS ERROR: the first version read the flag word with move.l (a0)+ - after
* a V1 block a0 sits on an odd address, and the 68000 stood there with guru
* 8000 0003. It is therefore read byte by byte; all other accesses through a0
* are bytes.
*
* SHADOW MODE (suffix m): the same routines, except that every writing place
* also sets `st 30720(a2)` - the byte of the same column in the first row of a
* sixth "plane" right behind the five. That is the change map.
* cvidp_copy_marked_asm at the end of the file then brings only what changed
* into the chip planes: one longword per 4-byte group when both halves changed,
* otherwise the single word. Why: on the A600 every chip bus cycle costs about
* 0.9 us, and half bytes written directly need two of them.
*
*
* Register use
*   a0 from   a1 cend   a2 q (plane 2)   a3 image of the left half
*   a4 V4 codebook      a5 V1 codebook   a6 state (cvidp_asmst)
*   d0 byte   d1-d4 entry offsets (index << 6)
*   d5 flag word   d6 bit counter   d7 blocks to the end of the row (word),
*                                 bit 31 = left half prepared

ST_FROM  equ 0
ST_CEND  equ 4
ST_Q     equ 8
ST_CB0   equ 12
ST_CB1   equ 16
ST_REM   equ 20                              ; ROWS to the end of the strip
ST_COL   equ 24
ST_WRAP  equ 28
ST_ROWS  equ 32
ST_BCOLS equ 36
ST_SCR   equ 40

        section code
''')

# --- gemeinsam: Register laden ---------------------------------------------
e('''* Load the registers from the state (a6 is already set).
cvidp_load:
        movea.l ST_FROM(a6),a0
        movea.l ST_CEND(a6),a1
        movea.l ST_Q(a6),a2
        movea.l ST_CB0(a6),a4
        movea.l ST_CB1(a6),a5
        move.l  ST_COL(a6),d7
        rts''')

def writers(x, mark):
    e(f'''
* Write an open left half, then the state back.
cvidp_finish{x}:
        btst    #0,d7
        beq.s   .store                       ; even: no half is open
        btst    #31,d7
        beq.s   .store
        bsr     cvidp_flush_left{x}
        bclr    #31,d7
.store:
        move.l  a0,ST_FROM(a6)
        move.l  a2,ST_Q(a6)
        move.l  d7,ST_COL(a6)
        rts

* Linke Haelfte allein (rechts uebersprungen): unteres Halbbyte bleibt.
cvidp_flush_left{x}:''')
    if mark: e(MK)
    for (r, k) in ORDER:
        i = r * P + k
        e(f'        move.b  {D(k,r)}(a2),d0')
        e(f'        andi.b  #$0F,d0')
        e(f'        or.b    {i}(a3),d0')
        e(f'        move.b  d0,{D(k,r)}(a2)')
    e('        rts')
    e('')

    # --- V1 ----------------------------------------------------------------
    e('* V1-Block, d1 = Index << 6 im V1-Codebook.')
    e(f'cvidp_emit_v1{x}:')
    e('        btst    #0,d7')
    e('        bne.s   .right')
    e('        lea     0(a5,d1.w),a3                ; finished image of the left position')
    e('        bset    #31,d7')
    e('        rts')
    e('.right:')
    if mark: e(MK)
    e('        btst    #31,d7')
    e('        beq     .pres')
    for (r, k) in ORDER:
        i = r * P + k
        e(f'        move.b  {i}(a3),d0')
        e(f'        or.b    {20+i}(a5,d1.w),d0')
        e(f'        move.b  d0,{D(k,r)}(a2)')
    e('        rts')
    e('.pres:                                       ; links uebersprungen: oberes Halbbyte bleibt')
    for (r, k) in ORDER:
        i = r * P + k
        e(f'        move.b  {D(k,r)}(a2),d0')
        e(f'        andi.b  #$F0,d0')
        e(f'        or.b    {20+i}(a5,d1.w),d0')
        e(f'        move.b  d0,{D(k,r)}(a2)')
    e('        rts')
    e('')

    # --- V4 ----------------------------------------------------------------
    e('* V4-Block, d1-d4 = Indizes << 6 im V4-Codebook.')
    e(f'cvidp_emit_v4{x}:')
    e('        btst    #0,d7')
    e('        bne     .right')
    e('        lea     ST_SCR(a6),a3')
    for (r, k) in ORDER:
        i = r * P + k
        ga, gb, ea, eb = LEFT4[r]
        e(f'        move.b  {G(ga,k)}(a4,{ea}.w),d0')
        e(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
        e(f'        move.b  d0,{i}(a3)')
    e('        bset    #31,d7')
    e('        rts')
    e('.right:')
    if mark: e(MK)
    e('        btst    #31,d7')
    e('        beq     .pres')
    for (r, k) in ORDER:
        i = r * P + k
        ga, gb, ea, eb = RIGHT4[r]
        e(f'        move.b  {i}(a3),d0')
        e(f'        or.b    {G(ga,k)}(a4,{ea}.w),d0')
        e(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
        e(f'        move.b  d0,{D(k,r)}(a2)')
    e('        rts')
    e('.pres:')
    for (r, k) in ORDER:
        ga, gb, ea, eb = RIGHT4[r]
        e(f'        move.b  {D(k,r)}(a2),d0')
        e(f'        andi.b  #$F0,d0')
        e(f'        or.b    {G(ga,k)}(a4,{ea}.w),d0')
        e(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
        e(f'        move.b  d0,{D(k,r)}(a2)')
    e('        rts')
    e('')

ADV = '''        subq.w  #1,d7                        ; Blockvorschub
        beq.s   .wr_%(n)s
        btst    #0,d7
        bne.s   .nx_%(n)s                     ; odd: the left one was due
        addq.l  #1,a2
        bclr    #31,d7
        bra.s   .nx_%(n)s
.wr_%(n)s:
        move.w  ST_BCOLS+2(a6),d7
        bclr    #31,d7
        adda.l  ST_WRAP(a6),a2
        subq.l  #1,ST_REM(a6)                ; one row less - check only here
        beq     .done
.nx_%(n)s:'''
FETCH1 = '''        moveq   #0,d1
        move.b  (a0)+,d1
        lsl.w   #6,d1'''
FETCH4 = '\n'.join(f'''        moveq   #0,{d}
        move.b  (a0)+,{d}
        lsl.w   #6,{d}''' for d in ('d1', 'd2', 'd3', 'd4'))
HAVE4 = '''        move.l  a0,d0
        addq.l  #4,d0
        cmp.l   a1,d0
        bhi     .done'''
FLAG = '''        move.b  (a0)+,d5                     ; flag word BYTE BY BYTE: a0 may be
        lsl.l   #8,d5                        ; odd, and a move.l from there is an
        move.b  (a0)+,d5                     ; address error on the 68000 (guru
        lsl.l   #8,d5                        ; 8000 0003) - as GETFLAG in
        move.b  (a0)+,d5                     ; cvid_blk8_000.s
        lsl.l   #8,d5
        move.b  (a0)+,d5'''

def loops(x):
    e(f'''* -------- 0x3200: V1 only -------------------------------------------------
        xdef    _cvidp_blk3200{x}
_cvidp_blk3200{x}:
        movem.l d2-d7/a2-a6,-(sp)
        movea.l 48(sp),a6
        bsr     cvidp_load
        tst.l   ST_REM(a6)
        beq     .done
.loop:
        cmpa.l  a1,a0
        bcc     .done
{FETCH1}
        bsr     cvidp_emit_v1{x}
{ADV % dict(n='a')}
        bra     .loop
.done:
        bsr     cvidp_finish{x}
        movem.l (sp)+,d2-d7/a2-a6
        rts

* -------- 0x3000: V1/V4, one flag bit per block -------------------------
        xdef    _cvidp_blk3000{x}
_cvidp_blk3000{x}:
        movem.l d2-d7/a2-a6,-(sp)
        movea.l 48(sp),a6
        bsr     cvidp_load
        tst.l   ST_REM(a6)
        beq     .done
.word:
{HAVE4}
{FLAG}
        moveq   #31,d6
.bit:
        add.l   d5,d5
        bcs.s   .v4
        cmpa.l  a1,a0
        bcc     .done
{FETCH1}
        bsr     cvidp_emit_v1{x}
        bra.s   .adv
.v4:
{HAVE4}
{FETCH4}
        bsr     cvidp_emit_v4{x}
.adv:
{ADV % dict(n='b')}
        dbf     d6,.bit
        bra     .word
.done:
        bsr     cvidp_finish{x}
        movem.l (sp)+,d2-d7/a2-a6
        rts

* -------- 0x3100: skip bit, then type bit, across word boundaries ---------
        xdef    _cvidp_blk3100{x}
_cvidp_blk3100{x}:
        movem.l d2-d7/a2-a6,-(sp)
        movea.l 48(sp),a6
        bsr     cvidp_load
        moveq   #0,d6                        ; no bits in the flag word
        tst.l   ST_REM(a6)
        beq     .done
.blk:
        tst.w   d6
        bne.s   .h1
{HAVE4}
{FLAG}
        moveq   #32,d6
.h1:
        subq.w  #1,d6
        add.l   d5,d5
        bcc.s   .skip
        tst.w   d6
        bne.s   .h2
{HAVE4}
{FLAG}
        moveq   #32,d6
.h2:
        subq.w  #1,d6
        add.l   d5,d5
        bcs.s   .v4
        cmpa.l  a1,a0
        bcc     .done
{FETCH1}
        bsr     cvidp_emit_v1{x}
        bra.s   .adv
.v4:
{HAVE4}
{FETCH4}
        bsr     cvidp_emit_v4{x}
        bra.s   .adv
.skip:
        btst    #0,d7                        ; links uebersprungen: nichts zu tun
        beq.s   .adv                         ; (the note is always empty there)
        btst    #31,d7
        beq.s   .adv
        bsr     cvidp_flush_left{x}          ; rechts uebersprungen, links offen
.adv:
{ADV % dict(n='c')}
        bra     .blk
.done:
        bsr     cvidp_finish{x}
        movem.l (sp)+,d2-d7/a2-a6
        rts''')

# --- Direkte Routinen: Paarschleifen ------------------------------------------
#
# The loop works IN PAIRS (two blocks = one plane byte per plane and row).
# Which kind the left half was is no longer held in d7 (bit 31, btst #0 per
# block) but in WHERE the code is running:
#   .L    linke Position, nichts offen
#   .RS   right, left skipped               (writes with preservation, upper nibble)
#   .R1   right, left V1 (a3 = entry)       (V1V1: row 1/3 = row 0/2)
#   .R4   right, left V4 (a3 = buffer)
# The writing instructions live in the pair, without bsr/rts.
#
# Flag bits with a guard bit: d5 holds the bits still open left-aligned, with a
# 1 below them. `add.l d5,d5` delivers the bit in the carry; if d5 is zero
# afterwards, what was shifted out was the guard bit - then reload the flag word
# (byte by byte, as before: a0 may be odd), `add.l` for the first bit and
# `bset #0` sets the new guard bit (bset changes only Z, the carry stays).
# That saves the bit counter d6, the tst.w and the subq.w per bit.
#
# 0x3100 TWO SKIPPED BLOCKS AT ONCE: at the left position d5 < $40000000 means
# that the top two bits are zero - and because the guard bit (a 1) lies below
# all open bits, both are real flag bits. The pair is skipped entirely: two
# bits gone, a2 further on.
#
# Register use (direct routines)
#   a0 from   a1 cend   a2 q (plane 2)   a3 image of the left half
#   a4 V4 codebook      a5 V1 codebook   a6 state (cvidp_asmst)
#   d0 byte   d1-d4 entry offsets (index << 6)   d2 also scratch
#   d5 flag bits with guard bit   d6 $40000000 (0x3000/0x3100)
#   d7 PAIRS to the end of the row (word)
# ST_COL stays "blocks to the end of the row" (2 * d7, on the right 2 * d7 - 1):
# odd means "right, left skipped" at the next chunk.
#
# TWO V1V1 PAIRS AS A WORD: if a V1V1 pair sits at an even byte column (d7
# even) and the next pair is V1V1 as well, both bytes per plane row are written
# as ONE word - one chip bus cycle instead of two. The following bits are looked
# at in advance: 0x3100 `1010` (coded V1, coded V1), 0x3000 `00`, each only when
# the guard bit lies below them, so that all four or two are real flag bits; on
# top of that two index bytes have to be there. Otherwise it carries on pair by
# pair - the same abort points as before. Word addresses are even: planes are
# even (cvidp_decode checks it), the column
# gerade.

# Options of the pair loops. cvidp_blk.s (for 68020 and up) stays without
# options, byte by byte as before. The 68000 player gets all of them, each one
# measured in the time model and checked against the plane dumps:
#   bits  bit 0 without a reload check: the guard only falls with carry = 1
#   v4d   V4 left without the 20-byte scratch buffer, mixed while writing
#   wrd   word pairs without lsl #8: the lower byte is overwritten, not or-ed
#   a3p   read entries with (a3)+ instead of a displacement
#   sk4   four skipped pairs in one step (0x3100)
#   dbf   pair counter with dbf instead of subq/bne
#   key2  Schnellweg V1V1|V1V1 an gerader Spalte (0x3000, Keyframes)
# GENOPT=a,b,... replaces the list for the 68000 files (GENOPT= : none).
OPT = set()
OPT68K = set(x for x in os.environ.get('GENOPT', 'bits,v4d,wrd,a3p,sk4,dbf,key2').split(',') if x)

def pair_loops(prefix='cvidp'):
    BITS = 'bits' in OPT; V4D = 'v4d' in OPT; WRD = 'wrd' in OPT; KEY = 'key' in OPT or 'key2' in OPT; KEY2 = 'key2' in OPT
    SK4 = 'sk4' in OPT; A3P = 'a3p' in OPT; DBF = 'dbf' in OPT
    NE = 'bpl' if DBF else 'bne'
    def w(s=''): e(s)
    def fetch(d):
        w(f'        moveq   #0,{d}'); w(f'        move.b  (a0)+,{d}'); w(f'        lsl.w   #6,{d}')
    def fetch1(): fetch('d1')
    def fetch4():
        for d in ('d1', 'd2', 'd3', 'd4'): fetch(d)
    def have1(fail): w('        cmpa.l  a1,a0'); w(f'        bcc     {fail}')
    def have4(fail):
        w('        move.l  a0,d0'); w('        addq.l  #4,d0'); w('        cmp.l   a1,d0'); w(f'        bhi     {fail}')
    refills = []
    def bit_cc(tag, fail, target):      # bit 0 -> target, bit 1 falls through
        w('        add.l   d5,d5')
        if BITS:
            w(f'        bcc     {target}'); w(f'        beq     .rf{tag}'); w(f'.c{tag}:')
        else:
            w(f'        beq     .rf{tag}'); w(f'.c{tag}:'); w(f'        bcc     {target}')
        refills.append((tag, fail, 'cc', target))
    def bit_cs(tag, fail, target):      # bit 1 -> target (with entry_cs), bit 0 falls through
        w('        add.l   d5,d5')
        if BITS:
            w(f'        bcs     {target}'); w(f'.c{tag}:')
        else:
            w(f'        beq     .rf{tag}'); w(f'.c{tag}:'); w(f'        bcs     {target}')
        refills.append((tag, fail, 'cs', target))
    def entry_cs(tag, label):
        w(f'{label}:')
        if BITS:
            w(f'        beq     .rf{tag}                     ; guard instead of bit 1'); w(f'{label}c:')
    def emit_refills():
        for tag, fail, mode, target in refills:
            w(f'.rf{tag}:')
            have4(fail)
            w('        move.b  (a0)+,d5                     ; byte by byte: a0 may be odd')
            w('        lsl.l   #8,d5')
            w('        move.b  (a0)+,d5')
            w('        lsl.l   #8,d5')
            w('        move.b  (a0)+,d5')
            w('        lsl.l   #8,d5')
            w('        move.b  (a0)+,d5')
            w('        add.l   d5,d5                        ; first bit into the carry')
            w('        bset    #0,d5                        ; Waechterbit, Carry bleibt')
            if BITS:
                if mode == 'cc': w(f'        bcc     {target}')
                else: w(f'        bcs     {target}c')
            w(f'        bra     .c{tag}')
        refills.clear()
    def gap(): w(f'        addq.l  #{P},a3')
    # --- Schreibbloecke ---------------------------------------------------------
    def write11():
        for r in (0, 2):
            for k in range(P):
                i = r * P + k
                w(f'        move.b  (a3)+,d0' if A3P else f'        move.b  {i}(a3),d0')
                w(f'        or.b    {4*P+i}(a5,d1.w),d0')
                w(f'        move.b  d0,{D(k,r)}(a2)')
                w(f'        move.b  d0,{D(k,r+1)}(a2)')
            if A3P and r == 0: gap()
    def write_double():
        for r in (0, 2):
            for k in range(P):
                i = r * P + k
                if WRD and k % 2 == 0:
                    w(f'        move.w  {i}(a3),d0                  ; even offset: word, lower byte follows')
                    w(f'        or.w    {4*P+i}(a5,d1.w),d0')
                    w(f'        move.b  {i}(a5,d2.w),d0')
                    w(f'        or.b    {4*P+i}(a5,d3.w),d0')
                elif WRD:
                    w(f'        move.b  {i}(a3),d0')
                    w(f'        or.b    {4*P+i}(a5,d1.w),d0')
                    w('        move.b  d0,-(sp)                     ; upper byte without lsl #8')
                    w('        move.w  (sp)+,d0')
                    w(f'        move.b  {i}(a5,d2.w),d0')
                    w(f'        or.b    {4*P+i}(a5,d3.w),d0')
                else:
                    w(f'        move.b  {i}(a3),d0')
                    w(f'        or.b    {4*P+i}(a5,d1.w),d0')
                    w('        lsl.w   #8,d0')
                    w(f'        or.b    {i}(a5,d2.w),d0')
                    w(f'        or.b    {4*P+i}(a5,d3.w),d0')
                w(f'        move.w  d0,{D(k,r)}(a2)')
                w(f'        move.w  d0,{D(k,r+1)}(a2)')
    def write_r1_after4():
        if V4D:     # d1-d4 left V4 indices, a3 -> right V1 entry row 0
            for r in (0, 2):
                for k in range(P):
                    for rr in (r, r + 1):
                        ga, gb, ea, eb = LEFT4[rr]
                        w(f'        move.b  {G(ga,k)}(a4,{ea}.w),d0')
                        w(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
                        w('        or.b    (a3),d0' if rr == r else '        or.b    (a3)+,d0')
                        w(f'        move.b  d0,{D(k,rr)}(a2)')
                if r == 0: gap()
            return
        for r in (0, 2):
            for k in range(P):
                i = r * P + k
                w(f'        move.b  {4*P+i}(a5,d1.w),d2')
                for rr in (r, r + 1):
                    w(f'        move.b  {rr*P+k}(a3),d0')
                    w('        or.b    d2,d0')
                    w(f'        move.b  d0,{D(k,rr)}(a2)')
    def write_r4():
        for (r, k) in ORDER:
            i = r * P + k
            ga, gb, ea, eb = RIGHT4[r]
            w('        move.b  (a3)+,d0' if A3P else f'        move.b  {i}(a3),d0')
            w(f'        or.b    {G(ga,k)}(a4,{ea}.w),d0')
            w(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
            w(f'        move.b  d0,{D(k,r)}(a2)')
    def write_44_direct(restore):   # left d1-d4, right from the stream
        w('        moveq   #0,d0'); w('        move.b  (a0)+,d0'); w('        lsl.w   #6,d0'); w('        movea.w d0,a3')
        fetch('d6')
        for r in (0, 1):
            for k in range(P):
                la, lb, ea, eb = LEFT4[r]; ra, rb, _, _ = RIGHT4[r]
                w(f'        move.b  {G(la,k)}(a4,{ea}.w),d0')
                w(f'        or.b    {G(lb,k)}(a4,{eb}.w),d0')
                w(f'        or.b    {G(ra,k)}(a4,a3.w),d0')
                w(f'        or.b    {G(rb,k)}(a4,d6.w),d0')
                w(f'        move.b  d0,{D(k,r)}(a2)')
        fetch('d1'); fetch('d2')      # right c, d; left a, b are no longer needed
        for r in (2, 3):
            for k in range(P):
                la, lb, ea, eb = LEFT4[r]; ra, rb, _, _ = RIGHT4[r]
                w(f'        move.b  {G(la,k)}(a4,{ea}.w),d0')
                w(f'        or.b    {G(lb,k)}(a4,{eb}.w),d0')
                w(f'        or.b    {G(ra,k)}(a4,d1.w),d0')
                w(f'        or.b    {G(rb,k)}(a4,d2.w),d0')
                w(f'        move.b  d0,{D(k,r)}(a2)')
        restore()
    def compose_l4():
        w(f'        lea     ST_SCR+{4*P}(a6),a3')
        for (r, k) in reversed(ORDER):
            ga, gb, ea, eb = LEFT4[r]
            w(f'        move.b  {G(ga,k)}(a4,{ea}.w),d0')
            w(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
            w('        move.b  d0,-(a3)')
    def flush_v1():
        for r in (0, 2):
            for k in range(P):
                w('        move.b  (a3)+,d2' if A3P else f'        move.b  {r*P+k}(a3),d2')
                for rr in (r, r + 1):
                    w(f'        move.b  {D(k,rr)}(a2),d0')
                    w('        andi.b  #$0F,d0')
                    w('        or.b    d2,d0')
                    w(f'        move.b  d0,{D(k,rr)}(a2)')
            if A3P and r == 0: gap()
    def flush_20():
        for (r, k) in ORDER:
            i = r * P + k
            w(f'        move.b  {D(k,r)}(a2),d0')
            w('        andi.b  #$0F,d0')
            if V4D:
                ga, gb, ea, eb = LEFT4[r]
                w(f'        or.b    {G(ga,k)}(a4,{ea}.w),d0')
                w(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
            else:
                w(f'        or.b    {i}(a3),d0')
            w(f'        move.b  d0,{D(k,r)}(a2)')
    def pres_v1():
        if A3P: w(f'        lea     {4*P}(a5,d1.w),a3')
        for r in (0, 2):
            for k in range(P):
                w('        move.b  (a3)+,d2' if A3P else f'        move.b  {4*P+r*P+k}(a5,d1.w),d2')
                for rr in (r, r + 1):
                    w(f'        move.b  {D(k,rr)}(a2),d0')
                    w('        andi.b  #$F0,d0')
                    w('        or.b    d2,d0')
                    w(f'        move.b  d0,{D(k,rr)}(a2)')
            if A3P and r == 0: gap()
    def pres_v4():
        for (r, k) in ORDER:
            ga, gb, ea, eb = RIGHT4[r]
            w(f'        move.b  {D(k,r)}(a2),d0')
            w('        andi.b  #$F0,d0')
            w(f'        or.b    {G(ga,k)}(a4,{ea}.w),d0')
            w(f'        or.b    {G(gb,k)}(a4,{eb}.w),d0')
            w(f'        move.b  d0,{D(k,r)}(a2)')

    def routine(kind):
        name = f'_{prefix}_blk{kind:04x}'
        flags = kind != 0x3200
        skip = kind == 0x3100
        key = KEY and kind == 0x3000
        def set_d6():
            if key: w('        move.l  a1,d6'); w('        subq.l  #4,d6                        ; d6 = Chunkende - 4')
            elif flags: w('        move.l  #$40000000,d6')
        w(f'* -------- 0x{kind:04x}, paarweise ' + '-' * 50)
        w(f'        xdef    {name}')
        w(f'{name}:')
        w('        movem.l d2-d7/a2-a6,-(sp)')
        w('        movea.l 48(sp),a6')
        w('        tst.l   ST_REM(a6)')
        w('        beq     .exit')
        w('        movea.l ST_FROM(a6),a0')
        w('        movea.l ST_CEND(a6),a1')
        w('        movea.l ST_Q(a6),a2')
        w('        movea.l ST_CB0(a6),a4')
        w('        movea.l ST_CB1(a6),a5')
        if flags: w('        move.l  #$80000000,d5                ; only the guard bit: no flag bit')
        set_d6()
        w('        move.l  ST_COL(a6),d7                ; blocks to the end of the row')
        w('        subq.w  #1,d7' if DBF else '        addq.w  #1,d7')
        w('        lsr.w   #1,d7                        ; pairs; carry free: blocks were odd')
        w('        bcc     .RS')
        w('.L:                                          ; links, nichts offen')
        if key:
            w('        cmpi.l  #$10000000,d5                ; 4 bits 0000, sentinel below it?')
            w('        bcs     .K')
            w('.Lb:')
        if skip:
            w('        cmp.l   d6,d5                        ; two skip bits zero?')
            w('        bcs     .pss')
            bit_cc('L0', '.dL', '.RS')
        if flags:
            bit_cs('L1', '.dL', '.L4')
        have1('.dL'); fetch1()
        w('        lea     0(a5,d1.w),a3')
        w('.R1:                                         ; rechts, links V1')
        if skip: bit_cc('R10', '.d1', '.R1s')
        if flags: bit_cs('R11', '.d1', '.R14')
        have1('.d1'); fetch1()
        if not key or KEY2:
            w('        btst    #0,d7                        ; gerade Spalte?')
            w('        beq     .w11' if DBF else '        bne     .w11')
            if skip:
                w('        move.l  d5,d0                        ; next 4 bits 1010, sentinel below it?')
                w('        subi.l  #$A0000001,d0')
                w('        cmpi.l  #$0FFFFFFE,d0                ; $A0000001..$AFFFFFFF')
                w('        bhi     .w11')
            elif key:
                w('        cmpi.l  #$40000000,d5                ; next 2 bits 00 (d6 is end of chunk - 4)')
                w('        bcc     .w11')
            elif flags:
                w('        cmp.l   d6,d5                        ; next 2 bits 00, sentinel below it?')
                w('        bcc     .w11')
            w('        move.l  a0,d0')
            w('        addq.l  #2,d0')
            w('        cmp.l   a1,d0')
            w('        bhi     .w11')
            for d in ('d2', 'd3'): fetch(d)
            if skip:    w('        lsl.l   #4,d5')
            elif flags: w('        lsl.l   #2,d5')
            write_double()
            w('        addq.l  #2,a2')
            w('        subq.w  #2,d7')
            w(f'        {NE}     .L')
            w('        bra     .wrap')
        w('.w11:')
        write11()
        w('        bra     .adv')
        if flags:
            entry_cs('R11', '.R14'); have4('.d1'); fetch4(); write_r4(); w('        bra     .adv')
            entry_cs('L1', '.L4'); have4('.dL'); fetch4()
            if not V4D: compose_l4()
            w('.R4:                                         ; rechts, links V4')
            if skip: bit_cc('R40', '.d4', '.R4s')
            bit_cs('R41', '.d4', '.R44')
            if V4D:
                have1('.d4')
                w('        moveq   #0,d0'); w('        move.b  (a0)+,d0'); w('        lsl.w   #6,d0')
                w(f'        lea     {4*P}(a5,d0.w),a3')
            else:
                have1('.d4'); fetch1()
            write_r1_after4(); w('        bra     .adv')
            entry_cs('R41', '.R44'); have4('.d4')
            if V4D: write_44_direct(set_d6)
            else: fetch4(); write_r4()
            w('        bra     .adv')
        if skip:
            w('.R1s:'); flush_v1(); w('        bra     .adv')
            w('.R4s:'); flush_20(); w('        bra     .adv')
        if key:
            w('.K:                                          ; Keyframe: V1V1|V1V1 an gerader Spalte')
            w('        btst    #0,d7')
            w('        beq     .Lb' if DBF else '        bne     .Lb')
            w('        cmpa.l  d6,a0                        ; four index bytes there?')
            w('        bhi     .Lb')
            w('        lsl.l   #4,d5')
            w('        moveq   #0,d0'); w('        move.b  (a0)+,d0'); w('        lsl.w   #6,d0'); w('        lea     0(a5,d0.w),a3')
            fetch('d1'); fetch('d2'); fetch('d3')
            write_double()
            w('        addq.l  #2,a2')
            w('        subq.w  #2,d7')
            w(f'        {NE}     .L')
            w('        bra     .wrap')
        w('.RS:                                         ; rechts, links uebersprungen')
        if skip: bit_cc('S0', '.dS', '.adv')
        if flags: bit_cs('S1', '.dS', '.RS4')
        have1('.dS'); fetch1(); pres_v1()
        if flags:
            w('        bra     .adv')
            entry_cs('S1', '.RS4'); have4('.dS'); fetch4(); pres_v4()
        if skip:
            w('        bra     .adv')
            w('.pss:                                        ; Paar ganz uebersprungen')
            if SK4:
                w('        cmpi.l  #$01000000,d5                ; four pairs skipped?')
                w('        bcc.s   .ps1')
                w('        cmpi.w  #3,d7' if DBF else '        cmpi.w  #4,d7')
                w('        bcs.s   .ps1')
                w('        lsl.l   #8,d5')
                w('        addq.l  #4,a2')
                w('        subq.w  #4,d7')
                w(f'        {NE}     .L')
                w('        bra     .wrap')
                w('.ps1:')
            w('        lsl.l   #2,d5')
        w('.adv:')
        w('        addq.l  #1,a2')
        if DBF: w('        dbf     d7,.L')
        else: w('        subq.w  #1,d7'); w('        bne     .L')
        w('.wrap:')
        w('        lea     4*40-40(a2),a2                ; next block row')
        w('        moveq   #39,d7' if DBF else '        moveq   #40,d7')
        w('        subq.l  #1,ST_REM(a6)                ; one row less')
        w('        bne     .L')
        w('.dL:                                         ; links, nichts offen: Bloecke = 2 * Paare')
        w('        moveq   #0,d0')
        w('        move.w  d7,d0')
        if DBF: w('        addq.w  #1,d0')
        w('        add.w   d0,d0')
        w('        bra     .store')
        w('.d1:                                         ; Chunkende, linke Haelfte V1 offen')
        flush_v1()
        w('        bra     .dS')
        if flags:
            w('.d4:                                         ; Chunkende, linke Haelfte V4 offen')
            flush_20()
        w('.dS:                                         ; rechts: Bloecke = 2 * Paare - 1')
        w('        moveq   #0,d0')
        w('        move.w  d7,d0')
        w('        add.w   d0,d0')
        w('        addq.w  #1,d0' if DBF else '        subq.w  #1,d0')
        w('.store:')
        w('        move.l  a0,ST_FROM(a6)')
        w('        move.l  a2,ST_Q(a6)')
        w('        move.l  d0,ST_COL(a6)')
        w('.exit:')
        w('        movem.l (sp)+,d2-d7/a2-a6')
        w('        rts')
        emit_refills()
        w('')
    routine(0x3200)
    routine(0x3000)
    routine(0x3100)

pair_loops()
e('')
e('* ==========================================================================')
e('* Shadow mode: the same routines with a change map')
e('* ==========================================================================')
writers('m', True)
loops('m')
e('')

# --- Kopieren ins Chip-RAM ----------------------------------------------------
def copy20(size, off):
    for (r, k) in ORDER:
        e(f'        move.{size}  {D(k,r)+off}(a3),{D(k,r)+off}(a4)')

e('''* -------- Copy what changed from the shadow into the target ----------------
*
* void cvidp_copy_marked_asm(cvidp_cpst *st)
*   0(st) src    shadow, plane 2, first row of the first block row
*   4(st) dst    target (chip RAM), likewise
*   8(st) brows  block rows
*
* The map lies at src + 30720. Ten 4-byte groups per block row, one longword of
* the map per group: zero - nothing to do; both word halves taken - copy 20
* longwords (5 planes x 4 rows); only one - 20 words. The map is cleared on the
* way. All addresses are even: rows at a distance of 160, groups at 4.
*
*
* Register use
*   a0 src block row    a1 dst block row   a2 map   a3/a4 src/dst group
*   d0 map group        d3 column          d7 block rows - 1
        xdef    _cvidp_copy_marked_asm
_cvidp_copy_marked_asm:
        movem.l d2-d7/a2-a6,-(sp)
        movea.l 48(sp),a6
        movea.l (a6),a0
        movea.l 4(a6),a1
        move.l  8(a6),d7
        beq     .done
        subq.l  #1,d7
.row:
        lea     30720(a0),a2
        moveq   #0,d3
.grp:
        move.l  (a2),d0
        beq     .next
        clr.l   (a2)
        lea     0(a0,d3.w),a3
        lea     0(a1,d3.w),a4
        tst.w   d0                           ; Bytes 2/3 geaendert?
        beq     .hi
        swap    d0
        tst.w   d0                           ; Bytes 0/1 geaendert?
        beq     .lo''')
copy20('l', 0)
e('        bra     .next')
e('.hi:                                         ; bytes 0/1 only')
copy20('w', 0)
e('        bra     .next')
e('.lo:                                         ; bytes 2/3 only')
copy20('w', 2)
e('''.next:
        addq.l  #4,a2
        addq.w  #4,d3
        cmpi.w  #40,d3
        bne     .grp
        lea     160(a0),a0
        lea     160(a1),a1
        dbf     d7,.row
.done:
        movem.l (sp)+,d2-d7/a2-a6
        rts

        end''')
# cvidp_blk.s (PLANAR of the C builds, cvidplanar.c) went away with the 020+
# rework. The routines above stay the basis of the pair loops and are still
# generated, but no longer written out.

# --- HAM6 LORES: the same pair loops for FOUR data planes ----------------------
#
# HAM6 at single width has the fixed control pattern B,G,R,G per pixel column
# (column mod 4). Cinepak blocks sit at multiples of 4 - so the control planes
# 4/5 are the same in EVERY frame ($DD/$77 per byte) and are written once when
# opening (cvidp_ham6_ctrl). Per frame the data planes 0-3 remain: the same
# memory layout as the 5-plane path, only P = 4. The entries (64 bytes, index
# << 6) have the same format with groups of 4 bytes: V1 left rows 0-3 at 0-15,
# right at 16-31; V4 groups 0-7 at 4 * g. What is inside them is built by
# src/asm/cvidh_mkcb.s (HAM instructions instead of palette indices) - the
# block loops see nothing of that.
o = []
setp(4)
e('''* cvidh_blk.s - Cinepak blocks straight into the 4 data planes of HAM6 LORES
*
* GENERATED by tools/gen_cvidp_blk.py - change it there, not here. The same
* pair loops as _cvidp_blk* in cvidp_blk.s (comment there and in the
* generator), only with 4 instead of 5 planes per block row: planes 0-3
* relative to plane 2 (-20480 .. +10360), V1 right at 16 instead of 20, buffer
* 16 bytes. The control planes 4/5 are never touched by this file.

ST_FROM  equ 0
ST_CEND  equ 4
ST_Q     equ 8
ST_CB0   equ 12
ST_CB1   equ 16
ST_REM   equ 20
ST_COL   equ 24
ST_WRAP  equ 28
ST_ROWS  equ 32
ST_BCOLS equ 36
ST_SCR   equ 40

        section code
''')
OPT = OPT68K
pair_loops('cvidh')
e('        end')
open('src/asm/cvidh_blk.s', 'w').write('\n'.join(o) + '\n')
print('lines HAM6:', len(o))

# --- 68000 player, 5 planes: the pair loops with all options -------------------
#
# A file of its own, so that cvidp_blk.s of the 020+ builds stays unchanged. The
# 68000 player links only this one (Makefile, A68K_OBJS).
o = []
setp(5)
e('''* cvidp_blk000.s - Cinepak-Bloecke direkt in 5 Bitplanes, 68000-Player
*
* GENERATED by tools/gen_cvidp_blk.py - change it there, not here. The same
* pair loops as in cvidp_blk.s, but with the options of the 68000 player
* (OPT68K in the generator). Without shadow mode and copy routine.

ST_FROM  equ 0
ST_CEND  equ 4
ST_Q     equ 8
ST_CB0   equ 12
ST_CB1   equ 16
ST_REM   equ 20
ST_COL   equ 24
ST_WRAP  equ 28
ST_ROWS  equ 32
ST_BCOLS equ 36
ST_SCR   equ 40

        section code
''')
pair_loops('cvidp')
e('        end')
open('src/asm/cvidp_blk000.s', 'w').write('\n'.join(o) + '\n')
print('lines 68000, 5 planes:', len(o))

# ==============================================================================
# 020/030 player and C builds from the 68040 on: the chipset modes of the rework
# ==============================================================================
#
# GRAY with 8 planes (AGA, 320 wide): the same pair loops with P = 8 and the
# options of the 68000 player. a2 points at plane 3, so planes 0-6 lie in the
# 16-bit range (-30720 .. +30840); plane 7 (+40960) needs a 32-bit displacement
# - vasm picks the full extension for it with -m68020.
o = []
setp(8)
BASEK = 3
e('''* cvxg8_blk.s - Cinepak-Bloecke direkt in 8 Bitplanes (GRAY, AGA), ab 68020
*
* GENERATED by tools/gen_cvidp_blk.py - change it there, not here. The same
* pair loops as cvidp_blk000.s, with 8 instead of 5 planes per block row. a2
* points at plane 3; plane 7 lies outside the 16-bit range and is addressed
* with a 32-bit displacement (68020 and up). Entries 64 bytes as there,
* generated by cvxg8_mkcb.s.

ST_FROM  equ 0
ST_CEND  equ 4
ST_Q     equ 8
ST_CB0   equ 12
ST_CB1   equ 16
ST_REM   equ 20
ST_COL   equ 24
ST_WRAP  equ 28
ST_ROWS  equ 32
ST_BCOLS equ 36
ST_SCR   equ 40

        section code
''')
OPT = OPT68K
pair_loops('cvxg8')
e('        end')
open('src/asm/cvxg8_blk.s', 'w').write('\n'.join(o) + '\n')
print('lines GRAY 8 planes:', len(o))
BASEK = 2


# --- DHAM6 and DHAM8: double width, a block is a whole byte -------------------
#
# Source column x occupies the screen columns 2x and 2x+1, and the pattern per
# screen column mod 4 is blue, green, red, green. A 4x4 block is 8 screen
# pixels, so exactly one byte per plane and row: no nibbles, no pairs, and a
# skipped block touches nothing. 80 bytes per row, plane 20480 bytes.
#
# Entries (64 bytes in size, the first 4 * GS are used), byte k of a group =
# data plane k, GS = 4 (DHAM6) or 8 (DHAM8):
#   V1  group 0 rows 0/1: B(y0) G(y0) R(y0) G(y0) B(y1) G(y1) R(y1) G(y1)
#       group 1 rows 2/3: the same with y2 y3
#   V4  group 0 = top << 4, group 1 = top, group 2 = bottom << 4,
#       group 3 = bottom; top = B(y0) G(y0) R(y1) G(y1), bottom with y2 y3
#   Row 0 = G0(a) | G1(b), row 1 = G2(a) | G3(b), rows 2/3 with c, d.
#
# Addressing: a2 points at plane 1 (planes 0-2), a3 at plane KB2 (the rest) -
# each +-20480 plus the row, 16 bit.
#
# Register use
#   a0 from   a1 cend   a2 plane 1   a3 plane KB2   a4 V4 codebook
#   a5 V1 codebook      a6 state (cvidp_asmst, ST_Q = a2)
#   d0 byte   d1-d4 entry offsets (index << 6)   d5 flag bits with guard bit
#   d7 blocks to the end of the row (word)
def byte_loops(prefix, PD, GS, KB2):
    RBb, BPLb, BCOLS = 80, 20480, 80
    dist = (KB2 - 1) * BPLb
    def w(s=''): e(s)
    def adr(k, r):
        if k < 3:
            return '%d(a2)' % ((k - 1) * BPLb + r * RBb)
        return '%d(a3)' % ((k - KB2) * BPLb + r * RBb)
    def fetch(d):
        w(f'        moveq   #0,{d}'); w(f'        move.b  (a0)+,{d}'); w(f'        lsl.w   #6,{d}')
    def emit_v1():
        for k in range(PD):
            w(f'        move.b  {k}(a5,d1.w),d0')
            w(f'        move.b  d0,{adr(k,0)}')
            w(f'        move.b  d0,{adr(k,1)}')
            w(f'        move.b  {GS+k}(a5,d1.w),d0')
            w(f'        move.b  d0,{adr(k,2)}')
            w(f'        move.b  d0,{adr(k,3)}')
    def emit_v4():
        for k in range(PD):
            for r, (ea, eb, ga, gb) in enumerate((('d1', 'd2', 0, 1), ('d1', 'd2', 2, 3),
                                                 ('d3', 'd4', 0, 1), ('d3', 'd4', 2, 3))):
                w(f'        move.b  {ga*GS+k}(a4,{ea}.w),d0')
                w(f'        or.b    {gb*GS+k}(a4,{eb}.w),d0')
                w(f'        move.b  d0,{adr(k,r)}')
    def have4(fail):
        w('        move.l  a0,d0'); w('        addq.l  #4,d0'); w('        cmp.l   a1,d0'); w(f'        bhi     {fail}')
    refills = []
    def bit(tag):                       # Bit ins Carry, Waechter nachladen
        w('        add.l   d5,d5')
        w(f'        beq     .rf{tag}')
        w(f'.c{tag}:')
        refills.append(tag)
    def routine(kind):
        name = f'_{prefix}_blk{kind:04x}'
        w(f'* -------- 0x{kind:04x} ' + '-' * 60)
        w(f'        xdef    {name}')
        w(f'{name}:')
        w('        movem.l d2-d7/a2-a6,-(sp)')
        w('        movea.l 48(sp),a6')
        w('        tst.l   ST_REM(a6)')
        w('        beq     .exit')
        w('        movea.l ST_FROM(a6),a0')
        w('        movea.l ST_CEND(a6),a1')
        w('        movea.l ST_Q(a6),a2')
        w('        movea.l a2,a3')
        w(f'        adda.l  #{dist},a3')
        w('        movea.l ST_CB0(a6),a4')
        w('        movea.l ST_CB1(a6),a5')
        w('        move.l  #$80000000,d5                ; only the guard bit')
        w('        move.l  ST_COL(a6),d7                ; blocks to the end of the row')
        w('.blk:')
        if kind == 0x3100:
            bit('0'); w('        bcc     .adv                         ; uebersprungen')
        if kind != 0x3200:
            bit('1'); w('        bcs     .v4')
        w('        cmpa.l  a1,a0')
        w('        bcc     .done')
        fetch('d1')
        emit_v1()
        if kind != 0x3200:
            w('        bra     .adv')
            w('.v4:')
            have4('.done')
            for d in ('d1', 'd2', 'd3', 'd4'): fetch(d)
            emit_v4()
        w('.adv:')
        w('        addq.l  #1,a2')
        w('        addq.l  #1,a3')
        w('        subq.w  #1,d7')
        w('        bne     .blk')
        w(f'        lea     {3*RBb}(a2),a2               ; next block row')
        w(f'        lea     {3*RBb}(a3),a3')
        w(f'        moveq   #{BCOLS},d7')
        w('        subq.l  #1,ST_REM(a6)')
        w('        bne     .blk')
        w('.done:')
        w('        move.l  a0,ST_FROM(a6)')
        w('        move.l  a2,ST_Q(a6)')
        w('        move.l  d7,ST_COL(a6)')
        w('.exit:')
        w('        movem.l (sp)+,d2-d7/a2-a6')
        w('        rts')
        for tag in refills:
            w(f'.rf{tag}:')
            have4('.done')
            w('        move.l  (a0)+,d5                     ; 68020 and up: also at an odd address')
            w('        add.l   d5,d5                        ; erstes Bit ins Carry')
            w('        bset    #0,d5                        ; Waechterbit, Carry bleibt')
            w(f'        bra     .c{tag}')
        refills.clear()
        w('')
    routine(0x3200)
    routine(0x3000)
    routine(0x3100)

for _prefix, _pd, _gs, _kb2, _name in (('cvxd6', 4, 4, 3, 'DHAM6'), ('cvxd8', 6, 8, 4, 'DHAM8')):
    o = []
    e(f'''* {_prefix}_blk.s - Cinepak blocks straight into the data planes of {_name}, 68020 and up
*
* GENERATED by tools/gen_cvidp_blk.py - change it there, not here. Double
* width: a block is a whole byte per plane and row ({_pd} data planes, 80 bytes
* per row, plane 20480 bytes). The control planes are never touched by this
* file. Entries are generated by {_prefix}_mkcb.s; format and registers in the generator.

ST_FROM  equ 0
ST_CEND  equ 4
ST_Q     equ 8
ST_CB0   equ 12
ST_CB1   equ 16
ST_REM   equ 20
ST_COL   equ 24

        section code
''')
    byte_loops(_prefix, _pd, _gs, _kb2)
    e('        end')
    open(f'src/asm/{_prefix}_blk.s', 'w').write('\n'.join(o) + '\n')
    print(f'lines {_name}:', len(o))
