#!/usr/bin/env python3
"""gen_a020_tabellen - build the tables of the 020/030 player.

Writes src/a020/tabellen.bin, tabellen.s (labels through incbin) and tabellen.i
(bounds of the large clamp tables). The computations come from
gen_a68k_tabellen.py (the same colour tables, the same rounding); the
68000 player is not touched by this.

  UB UG VR VG yTab     256 int16 each (tab_wort = yTab; UB -2048, UG -1536,
                       VR -1024, VG -512), chroma indexed with the RAW u/v byte
  patblk               65536 bytes (tab_pat = middle): pattern for GRAY 5 planes
  n4hi n4lo            1408 bytes each, HAM6 level << 4 and level, rounded
  h6tab                4096 bytes: per pair of two 4-bit levels the four
                       plane bytes with the bits at 7-6/3-2 and 5-4/1-0
  l6                   1408 bytes, HAM8 level min(63, (v+2)>>2)
  c8 a8                256 x 8 bytes each: byte k = $C0 and $80 when bit k of
                       the grey value is set (GRAY 8 planes)
  yuv32                ub vr ug vg yTab, 256 int32 each, indexed naturally
                       (tab_yuv32 = yTab; ub -4096 ... vg -1024) - the format
                       of the chunky codebooks for RTG (cvid_mkcb_common.i)
  rng                  1408 bytes rngLimit (tab_rng = index 0); from it
                       cvid_open builds the clamp tables for RGB32/RGB16

The pair tables for DHAM8 (4096 x 8 bytes, twice) and the large clamp tables
are built by cvid_open at runtime.
Call: python3 tools/gen_a020_tabellen.py"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_a68k_tabellen as t68  # noqa: E402

OUT = os.path.join(os.path.dirname(HERE), 'src', 'a020')
BIAS, SIZE = t68.BIAS, t68.SIZE


def h6(v):
    return min(63, (v + 2) >> 2)


def bitvec(maske):
    b = bytearray(256 * 8)
    for v in range(256):
        for k in range(8):
            if (v >> k) & 1:
                b[8 * v + k] = maske
    return bytes(b)


def grenzen():
    g = t68.grenzen()
    ub, vr, ug, vg, yt = t68.yuv_tables()
    cg = [a + b for a in ug for b in vg]
    alle = ub + vr + cg
    g = {'N4HI': g['N4HI'], 'N4LO': g['N4LO'], 'L6': (min(alle), max(yt) + max(alle))}
    return g


def main():
    data = bytearray()
    ub, vr, ug, vg, yt = t68.yuv_tables()
    roh = lambda t: [t[u ^ 0x80] for u in range(256)]
    for t in (roh(ub), roh(ug), roh(vr), roh(vg), yt):
        data += struct.pack('>256h', *t)
    data += t68.patterns()
    data += bytes(t68.h4(t68.rng(i)) << 4 for i in range(SIZE))
    data += bytes(t68.h4(t68.rng(i)) for i in range(SIZE))
    data += t68.h6tab()
    data += bytes(h6(t68.rng(i)) for i in range(SIZE))
    data += bitvec(0xC0)
    data += bitvec(0x80)
    for t in (ub, vr, ug, vg, yt):
        data += struct.pack('>256i', *t)
    data += bytes(t68.rng(i) for i in range(SIZE))
    open(os.path.join(OUT, 'tabellen.bin'), 'wb').write(data)

    parts = [(None, 4 * 512), ('tab_wort', 512),
             (None, 32768), ('tab_pat', 32768),
             (None, BIAS), ('tab_n4hi', SIZE - BIAS), (None, BIAS), ('tab_n4lo', SIZE - BIAS),
             ('tab_h6', 4096),
             (None, BIAS), ('tab_l6', SIZE - BIAS),
             ('tab_c8', 2048), ('tab_a8', 2048),
             (None, 4 * 1024), ('tab_yuv32', 1024),
             (None, BIAS), ('tab_rng', SIZE - BIAS)]
    assert sum(n for _, n in parts) == len(data)
    lines = ['; tabellen.s - GENERATED by tools/gen_a020_tabellen.py, do not edit by hand.',
             '', '        section tabellen,data', '',
             '        xdef    ' + ','.join(n for n, _ in parts if n), '']
    off = 0
    for name, n in parts:
        lab = (name + ':') if name else ''
        lines.append('%-12s incbin  "tabellen.bin",%d,%d' % (lab, off, n))
        off += n
    open(os.path.join(OUT, 'tabellen.s'), 'w').write('\n'.join(lines) + '\n')
    inc = ['; tabellen.i - GENERATED by tools/gen_a020_tabellen.py, do not edit by hand.',
           '; Large clamp tables: index (_y + c) from LO to LO + LEN - 1.', '']
    for k, (lo, hi) in grenzen().items():
        assert -32768 <= lo and hi <= 32767 and hi - lo + 1 <= 65535, k
        inc.append('GR_%s_LO  equ %d' % (k, lo))
        inc.append('GR_%s_LEN equ %d' % (k, hi - lo + 1))
    open(os.path.join(OUT, 'tabellen.i'), 'w').write('\n'.join(inc) + '\n')
    print('tabellen.bin: %d bytes' % len(data))


if __name__ == '__main__':
    main()
